PREFIX    = $(DEVKITARM)/bin/arm-none-eabi
CC        = $(PREFIX)-gcc
CXX       = $(PREFIX)-g++
AR        = $(PREFIX)-ar

SRCS+=./ammo.cpp
SRCS+=./ammohistory.cpp
SRCS+=./ammo_secondary.cpp
SRCS+=./battery.cpp
SRCS+=./buy_preset.cpp
SRCS+=./buy_presets.cpp
SRCS+=./buy_preset_debug.cpp
SRCS+=./buy_preset_weapon_info.cpp
SRCS+=./cdll_int.cpp
SRCS+=./com_weapons.cpp
SRCS+=./cvar_checker.cpp
SRCS+=./death.cpp
SRCS+=./demo.cpp
SRCS+=./draw_util.cpp
SRCS+=./entity.cpp
SRCS+=./events.cpp
SRCS+=./ev_common.cpp
#SRCS+=./ev_hldm.cpp
SRCS+=./flashlight.cpp
SRCS+=./GameStudioModelRenderer.cpp
SRCS+=./geiger.cpp
SRCS+=./health.cpp
SRCS+=./hud.cpp
SRCS+=./hud_msg.cpp
SRCS+=./hud_redraw.cpp
SRCS+=./hud_spectator.cpp
SRCS+=./hud_update.cpp
SRCS+=./hud_vgui2print.cpp
SRCS+=./input.cpp
#SRCS+=./inputw32.cpp
SRCS+=./interpolation.cpp
SRCS+=./in_camera.cpp
SRCS+=./menu.cpp
SRCS+=./message.cpp
SRCS+=./nightvision.cpp
SRCS+=./rain.cpp
SRCS+=./saytext.cpp
SRCS+=./ScenarioStatus.cpp
SRCS+=./SniperScope.cpp
SRCS+=./statusbar.cpp
SRCS+=./status_icons.cpp
SRCS+=./StudioModelRenderer.cpp
SRCS+=./studio_util.cpp
SRCS+=./text_message.cpp
SRCS+=./train.cpp
SRCS+=./tri.cpp
SRCS+=./unicode_strtools.cpp
SRCS+=./util.cpp
SRCS+=./vgui_parser.cpp
SRCS+=./view.cpp
SRCS+=./z_weather.cpp
#SRCS+=./cs_wpn/cs_baseentity.cpp
SRCS+=./cs_wpn/cs_weapons.cpp
SRCS+=./events/event_ak47.cpp
SRCS+=./events/event_aug.cpp
SRCS+=./events/event_awp.cpp
SRCS+=./events/event_createexplo.cpp
SRCS+=./events/event_createsmoke.cpp
SRCS+=./events/event_czerods.cpp
SRCS+=./events/event_deagle.cpp
SRCS+=./events/event_decal_reset.cpp
SRCS+=./events/event_elite.cpp
SRCS+=./events/event_famas.cpp
SRCS+=./events/event_fiveseven.cpp
SRCS+=./events/event_g3sg1.cpp
SRCS+=./events/event_galil.cpp
SRCS+=./events/event_glock18.cpp
SRCS+=./events/event_knife.cpp
SRCS+=./events/event_m249.cpp
SRCS+=./events/event_m3.cpp
SRCS+=./events/event_m4a1.cpp
SRCS+=./events/event_mac10.cpp
SRCS+=./events/event_mp5n.cpp
SRCS+=./events/event_p228.cpp
SRCS+=./events/event_p90.cpp
SRCS+=./events/event_scout.cpp
SRCS+=./events/event_sg550.cpp
SRCS+=./events/event_sg552.cpp
SRCS+=./events/event_tmp.cpp
SRCS+=./events/event_ump45.cpp
SRCS+=./events/event_usp.cpp
SRCS+=./events/event_vehicle.cpp
SRCS+=./events/event_xm1014.cpp
SRCS+=./events/ev_cs16.cpp
SRCS+=./hl/hl_baseentity.cpp
SRCS+=./hl/hl_events.cpp
SRCS+=./hl/hl_objects.cpp
SRCS+=./hl/hl_weapons.cpp
SRCS+=./hud/money.cpp
SRCS+=./hud/MOTD.cpp
SRCS+=./hud/nvg.cpp
SRCS+=./hud/radar.cpp
SRCS+=./hud/radio.cpp
SRCS+=./hud/scenario.cpp
SRCS+=./hud/scoreboard.cpp
SRCS+=./hud/sniperscope.cpp
SRCS+=./hud/spectator_gui.cpp
SRCS+=./hud/timer.cpp
#SRCS+=./input/input_sdl.cpp
SRCS+=./input/input_xash3d.cpp
SRCS+=./input/input_mouse.cpp
SRCS+=./VGUI/backgroundpanel.cpp
SRCS+=./VGUI/basecareermenu.cpp
SRCS+=./VGUI/buymenu.cpp
SRCS+=./VGUI/buypresetimageinfo.cpp
SRCS+=./VGUI/buypresetpanel.cpp
SRCS+=./VGUI/buypreset_editmenu.cpp
SRCS+=./VGUI/buypreset_listbox.cpp
SRCS+=./VGUI/buypreset_mainmenu.cpp
SRCS+=./VGUI/buysubmenu.cpp
SRCS+=./VGUI/CareerBox.cpp
SRCS+=./VGUI/careermatchendmenu.cpp
SRCS+=./VGUI/careerroundendmenu.cpp
SRCS+=./VGUI/counterstrikeviewport.cpp
SRCS+=./VGUI/counterstrikeviewport_interface.cpp
SRCS+=./VGUI/creditsmenu.cpp
SRCS+=./VGUI/CSProgressBar.cpp
SRCS+=./VGUI/cstrikeclassmenu.cpp
SRCS+=./VGUI/cstrikeclientscoreboard.cpp
SRCS+=./VGUI/cstrikespectatorgui.cpp
SRCS+=./VGUI/cstriketeammenu.cpp
SRCS+=./VGUI/cstriketeammenu.cpp
SRCS+=../dlls/wpn_shared/wpn_ak47.cpp
SRCS+=../dlls/wpn_shared/wpn_aug.cpp
SRCS+=../dlls/wpn_shared/wpn_awp.cpp
SRCS+=../dlls/wpn_shared/wpn_c4.cpp
SRCS+=../dlls/wpn_shared/wpn_deagle.cpp
SRCS+=../dlls/wpn_shared/wpn_elite.cpp
SRCS+=../dlls/wpn_shared/wpn_famas.cpp
SRCS+=../dlls/wpn_shared/wpn_fiveseven.cpp
SRCS+=../dlls/wpn_shared/wpn_flashbang.cpp
SRCS+=../dlls/wpn_shared/wpn_g3sg1.cpp
SRCS+=../dlls/wpn_shared/wpn_galil.cpp
SRCS+=../dlls/wpn_shared/wpn_glock18.cpp
SRCS+=../dlls/wpn_shared/wpn_hegrenade.cpp
SRCS+=../dlls/wpn_shared/wpn_knife.cpp
SRCS+=../dlls/wpn_shared/wpn_m249.cpp
SRCS+=../dlls/wpn_shared/wpn_m3.cpp
SRCS+=../dlls/wpn_shared/wpn_m4a1.cpp
SRCS+=../dlls/wpn_shared/wpn_mac10.cpp
SRCS+=../dlls/wpn_shared/wpn_mp5navy.cpp
SRCS+=../dlls/wpn_shared/wpn_p228.cpp
SRCS+=../dlls/wpn_shared/wpn_p90.cpp
SRCS+=../dlls/wpn_shared/wpn_scout.cpp
SRCS+=../dlls/wpn_shared/wpn_sg550.cpp
SRCS+=../dlls/wpn_shared/wpn_sg552.cpp
SRCS+=../dlls/wpn_shared/wpn_smokegrenade.cpp
SRCS+=../dlls/wpn_shared/wpn_tmp.cpp
SRCS+=../dlls/wpn_shared/wpn_ump45.cpp
SRCS+=../dlls/wpn_shared/wpn_usp.cpp
SRCS+=../dlls/wpn_shared/wpn_xm1014.cpp
SRCS+=../pm_shared/pm_debug.cpp
SRCS+=../pm_shared/pm_math.cpp
SRCS+=../pm_shared/pm_shared.cpp

# Miniutl
SRCS+=../../mainui_3ds/miniutl/bitstring.cpp
SRCS+=../../mainui_3ds/miniutl/generichash.cpp
SRCS+=../../mainui_3ds/miniutl/utlbuffer.cpp
SRCS+=../../mainui_3ds/miniutl/strtools.cpp
SRCS+=../../mainui_3ds/miniutl/utlmemory.cpp

OBJS = $(SRCS:.cpp=.o) $(SRCS_C:.c=.o)

INCLUDES = -I. -I./include -I./include/hud -I./include/math -I./include/studio -I./VGUI -I./input -I../dlls \
	-I../cl_dll \
	-I../common \
	-I../engine \
	-I../pm_shared \
	-I../dlls \
	-I../game_shared \
	-I../public \
	-I../public/cl_dll \
	-I../../mainui_3ds \
	-I../../mainui_3ds/controls \
	-I../../mainui_3ds/menus \
	-I../../mainui_3ds/miniutl
DEFINES = -Dstricmp=strcasecmp -D_strnicmp=strncasecmp -Dstrnicmp=strncasecmp -D_snprintf=snprintf -DCLIENT_WEAPONS -DCLIENT_DLL -D__3DS__ \
	-Dstrcasestr=strstr
CFLAGS =  -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O2 -Wl,-q -Wfatal-errors -Wno-write-strings -fsigned-char -fno-short-enums -ffunction-sections -fdata-sections  $(DEFINES) $(INCLUDES)
CXXFLAGS = $(CFLAGS) -fno-exceptions -std=gnu++14 -fno-threadsafe-statics -fpermissive -static-libstdc++ -static-libgcc
ASFLAGS = $(CFLAGS)

all: libclient.a

libclient.a: $(OBJS)
	$(AR) rcs $@ $^

clean:
	@rm -rf libclient.a $(OBJS)

$(DEPSDIR):
	@mkdir -p $@